# Generated by Django 4.0.5 on 2022-06-17 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_classroom_semester_alter_classroom_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.userprofile'),
            preserve_default=False,
        ),
    ]
