# Generated by Django 4.0.5 on 2022-06-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_classroom_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='semester',
        ),
    ]
