# Generated by Django 4.0.5 on 2022-06-19 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
