# Generated by Django 4.0.5 on 2022-08-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='edu_qualification',
            new_name='education_qualification',
        ),
    ]
