# Generated by Django 4.0.5 on 2022-08-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_edu_qualification_faculty_education_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='honors_awards',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='publications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_interests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='responsibliites',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
