# Generated by Django 4.0.5 on 2022-08-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_faculty_honors_awards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='responsibliites',
            new_name='other_responsibliites',
        ),
    ]
