# Generated by Django 4.0.5 on 2022-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_faculty_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
