# Generated by Django 4.0.5 on 2022-08-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_student_semester_alter_faculty_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='education_qualification',
            new_name='educational_qualification',
        ),
    ]
