# Generated by Django 4.0.5 on 2022-08-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_education_qualification_faculty_educational_qualification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
