# Generated by Django 4.0.5 on 2022-08-04 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
