# Generated by Django 4.0.5 on 2022-08-04 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('phone_number', models.CharField(max_length=20)),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='1', max_length=6, verbose_name='Title')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('educational_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('honors_awards', models.CharField(blank=True, max_length=200, null=True)),
                ('research_interests', models.CharField(blank=True, max_length=200, null=True)),
                ('publications', models.CharField(blank=True, max_length=200, null=True)),
                ('other_responsibliites', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
