# Generated by Django 4.0.5 on 2022-08-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_semester_course_remove_subject_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
