# Generated by Django 4.0.5 on 2022-08-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={},
        ),
    ]
