# Generated by Django 4.0.5 on 2022-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_classroom_course_semester_remove_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Class code'),
        ),
    ]
