# Generated by Django 4.0.5 on 2022-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_classroom_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Course code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Subject code'),
        ),
    ]
