# Generated by Django 4.0.5 on 2022-06-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_course_course_code_alter_subject_subject_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='class_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='class_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
    ]
