# Generated by Django 4.0.5 on 2022-06-15 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_class_code_classroom_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stream',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.userprofile'),
            preserve_default=False,
        ),
    ]
